src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('view/', views.view_cart, name='view_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
]

src/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns =[
    path('', views.browse, name='browse'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.info, name='info'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shoppers.urls')),
    path('products/', include('products.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('cart/', include('cart.urls', namespace='cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=300)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='products_images',blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User, related_name='products', on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

src/products/forms.py
from django import forms

from . models import Product

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class NewProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'description', 'price', 'image')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'description', 'price', 'image', 'is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

src/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Product, Category
from django.db.models import Q
from .forms import NewProductForm, EditProductForm

def browse(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    browse = Product.objects.filter(is_sold=False)

    if category_id:
        browse = browse.filter(category_id=category_id)

    if query:
        browse = browse.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )

    return render(request, 'products/browse.html', {
        'browse': browse,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })

def info(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(
        category=product.category, is_sold=False
    ).exclude(pk=pk)[0:5]

    return render(request, 'products/info.html', {
        'product': product,
        'related_products': related_products,
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)

        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()

            return redirect('products:info', pk=product.pk)
        
    else:
        form = NewProductForm()

    return render(request, 'products/form.html', {
        'form': form,
        'title': 'New Product',
    })

@login_required
def edit(request, pk):
    products = get_object_or_404(Product, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=products)

        if form.is_valid():
            form.save()

            return redirect('products:info', pk=products.id)
        
    else:
        form = EditProductForm(instance=products)

    return render(request, 'products/form.html', {
        'form': form,
        'title': 'Edit Product',
    })

@login_required
def delete(request, pk):
    products = get_object_or_404(Product, pk=pk, created_by=request.user)
    products.delete()

    return redirect('dashboard:index')

src/products/templates/products/browse.html
{% extends 'shoppers/base.html' %}

{% block title %}Browse{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'products:browse' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'products:browse' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'products:browse' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for product in browse %}
                    <div>
                        <a href="{% url 'products:info' product.id %}">
                            <div>
                                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ product.name }}</h2>
                                <p class="text-gray-500">Price: ${{ product.price|floatformat:2 }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

src/products/templates/products/form.html
{% extends 'shoppers/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors}}
        </div>
    {% endif %}
    
    <button class="mt-6 py-4 px-7 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock%}

src/products/templates/products/info.html
{% extends 'shoppers/base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-5">
    <div class="col-span-3">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ product.name}}</h1>
        <p class="text-gray-500"><strong>Price: </strong> ${{ product.price|floatformat:2 }}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ product.created_by.username}}</p>

        {% if product.description %}
            <p class="text-gray-600">
                <strong class="text-gray-500">Description:</strong><br>
                {{ product.description}}
            </p>
        {% endif %}

        {% if request.user == product.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your product!</p>

                <a href="{% url 'products:edit' product.id %}" class="inline-block mt-6 px-6 py3 text-lg font-semibold bg-violet-500 text-white hover:bg-violet-700 rounded-xl">Edit</a>
                <a href="{% url 'products:delete' product.id %}" class="inline-block mt-6 px-6 py3 text-lg font-semibold bg-red-500 text-white hover:bg-red-700 rounded-xl">Delete</a>

            </div>
        {% else %}
            <a href="#" class="inline-block mt-6 px-6 py3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Contact seller</a>
            <a href="{% url 'cart:add_to_cart' product.id %}" class="inline-block mt-6 px-6 py3 text-lg font-semibold bg-yellow-500 text-white hover:bg-yellow-700 rounded-xl">Add to cart</a>
        {% endif %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related products</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for product in related_products %}
            <div>
                <a href="{% url 'products:info' product.id %}">
                    <div>
                        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="w-full h-64 object-cover rounded-xl">
                    </div>
                    <div class="p-6 bg-white rounded-xl">
                        <h2 class="text-2xl">{{ product.name }}</h2>
                        <p class="text-gray-500">Price: ${{ product.price|floatformat:2 }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock%}