src/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('view/', views.view_cart, name='view_cart'),
    path('remove/<int:cart_item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
]

src/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns =[
    path('', views.browse, name='browse'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.info, name='info'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

src/shoppers/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from . forms import LoginForm

app_name = 'shoppers'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('follow_us/', views.follow_us, name='follow_us'),
    path('terms/', views.terms, name='terms'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='shoppers/login.html', authentication_form=LoginForm), name='login'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shoppers.urls')),
    path('products/', include('products.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('cart/', include('cart.urls', namespace='cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shoppers/models.py
from django.db import models

# Create your models here.

src/shoppers/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class LogoutForm(forms.Form):
    pass

src/shoppers/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.contrib.auth import logout as auth_logout

from products.models import Product, Category
from .forms import SignupForm, LogoutForm

def index(request):
    products = Product.objects.filter(is_sold=False)[0:7]
    categories = Category.objects.all()
    return render(request, 'shoppers/index.html', {
        'products': products,
        'categories': categories
    })

def follow_us(request):
    return render(request, 'shoppers/follow_us.html')

def terms(request):
    return render(request, 'shoppers/terms.html')

def contact(request):
    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']
        from_email = request.POST['email']
        send_mail(subject, message, from_email, [''])
        return HttpResponseRedirect('/contact/')
    return render(request, 'shoppers/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'shoppers/signup.html', {
        'form': form
    })

def user_logout(request):
    form = LogoutForm()

    if request.method == 'POST':
        form = LogoutForm(request.POST)
        if form.is_valid():
            auth_logout(request)
            return redirect('/login/')

    return render(request, 'shoppers/logout.html', {
        'form': form
    })

src/shoppers/templates/shoppers/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} | Shoppers</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-600">
            <a href="/" class="text-3xl font-semibold">Shoppers</a>
            <div class="flex-grow text-right px-4 py-2 m-2">
                <!-- Add the toggle icon here -->
                <button id="toggle-button" class="toggle-button bg-transparent border-none cursor-pointer">
                    <i class="toggle-icon text-2xl"></i>
                </button>
                <!-- End of toggle icon -->
                <a href="{%url 'cart:view_cart' %}" class="text-lg px-2 rounded hover:bg-gray-700">Cart</a>
                <a href="{% url 'products:browse' %}" class="text-lg px-2 rounded hover:bg-gray-700">Search</a>
                <a href="{% url 'products:new' %}" class="text-lg px-2 rounded hover:bg-gray-700">New products</a>

                {% if request.user.is_authenticated%}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <a href="{% url 'shoppers:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
                {% else %}
                    <a href="{% url 'shoppers:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'shoppers:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
                {% endif %}  
            </div>
        </nav>
        <div class="px-6 py-6" >
            {% block content %}
            {% endblock %}
        </div>
        <!-- FOOTER -->
        <footer class="px-6 py-6 flex-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-400 space-y-2">
                    Welcome to the shoppers website where  every shoppers needs are met.
                </p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About us</a></li>
                    <li><a href="{% url 'shoppers:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="{%url 'shoppers:terms' %}" class="text-lg text-teal-500 hover:text-teal-700">Terms & conditions</a></li>
                    <li><a href="{% url 'shoppers:follow_us' %}" class="text-lg text-teal-500 hover:text-teal-700">Follow us</a></li>
                </ul>
            </div>
        </footer>
        <script>
            const toggleButton = document.getElementById("toggle-button");
            const toggleIcon = document.querySelector(".toggle-icon");
        
            let isToggled = false;
        
            toggleButton.addEventListener("click", () => {
                isToggled = !isToggled;
                if (isToggled) {
                    // Code to handle the toggle ON state
                    toggleIcon.classList.add("active");
                    // Perform the necessary actions when the toggle is on
                } else {
                    // Code to handle the toggle OFF state
                    toggleIcon.classList.remove("active");
                    // Perform the necessary actions when the toggle is off
                }
            });
        </script>        
    </body>
</html>

src/shoppers/templates/shoppers/contact.html
{% extends 'shoppers/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Learn more by contacting us</h1>
    <section>
        <h2>Contact Information</h2>
        <p>If you have any questions or need assistance, please don't hesitate to get in touch with us. Our customer support team is here to help you.</p>
        <address>
            <strong>Shoppers</strong><br>
            123 Shopper's Lane<br>
            City, State, ZIP Code<br>
            <br>
            Phone: (123) 456-7890<br>
            Email: info@shoppers.com<br>
        </address>
    </section>

    <section>
        <h2>Contact Form</h2>
        <p>You can also reach us by using the contact form below:</p>
        <form method="post" action="{% url 'shoppers:contact' %}">
            {% csrf_token %}
            <div class="mb-4">
                <label for="name" class="block text-gray-700 text-sm font-bold mb-2">Name:</label>
                <input type="text" id="name" name="name" required placeholder="Enter your name" class="w-full px-2 py-1 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500">
            </div>
    
            <div class="mb-4">
                <label for="email" class="block text-gray-700 text-sm font-bold mb-2">Email:</label>
                <input type="email" id="email" name="email" required placeholder="Enter your email" class="w-full px-2 py-1 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500">
            </div>
    
            <div class="mb-4">
                <label for="subject" class="block text-gray-700 text-sm font-bold mb-2">Subject:</label>
                <input type="text" id="subject" name="subject" required placeholder="Provides a brief title" class="w-full px-2 py-1 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500">
            </div>
    
            <div class="mb-4">
                <label for="message" class="block text-gray-700 text-sm font-bold mb-2">Message:</label>
                <textarea id="message" name="message" rows="4" required placeholder="Enter your message" class="w-full px-2 py-1 text-gray-700 border rounded-lg focus:outline-none focus:border-blue-500"></textarea>
            </div>
    
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 text-lg font-semibold rounded-lg hover:bg-blue-700">Submit</button>
        </form>
    </section>
    
    
    <footer>
        <p>Thank you for shopping with Shoppers. We look forward to assisting you!</p>
    </footer>
{% endblock %}

src/shoppers/templates/shoppers/follow_us.html
{% extends 'shoppers/base.html' %}

{% block title %}Follow us{% endblock %}

{% block content %}
    <h1 class="text-2xl font-semibold">Follow us</h1>
    <div class="mb-0.5rem text-lg text-blue-500 hover:text-teal-700">
        <li><a href="https://www.facebook.com"><i class="fab fa-facebook"></i>facebook</a></li>
        <li><a href="https://twitter.com"><i class="fab fa-twitter">twitter</i></a></li>
        <li><a href="https://www.instagram.com"><i class="fab fa-instagram">instagram</a></li>
        <li><a href="https://www.youtube.com"><i class="fab fa-youtube">youtube</a></li> 
    </div>
{% endblock %}

src/shoppers/templates/shoppers/index.html
{% extends 'shoppers/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Latest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in products %}
                <div>
                    <a href="{% url 'products:info' product.id %}">
                        <div>
                            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="w-full h-64 object-cover rounded-xl">
                        </div>
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ product.name }}</h2>
                            <p class="text-gray-500">Price: ${{ product.price|floatformat:2 }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.products.count }} products</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/shoppers/templates/shoppers/login.html
{% extends 'shoppers/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 p-5 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username}}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors}}
            </div>
        {% endif %}

        <button class="py-4 px-7 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

src/shoppers/templates/shoppers/logout.html
{% extends 'shoppers/base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}
    <p>Are you sure you want to logout?</p>

    <form method="post" action="{% url 'shoppers:logout' %}">
        {% csrf_token %}
        <button class="py-4 px-7 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Logout</button>
    </form>
{% endblock %}

src/shoppers/templates/shoppers/signup.html
{% extends 'shoppers/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 p-5 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors}}
            </div>
        {% endif %}

        <button class="py-4 px-7 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

src/shoppers/templates/shoppers/terms.html
{% extends 'shoppers/base.html' %}

{% block title %}Terms{% endblock %}

{% block content %}
    <h1>Terms and Conditions</h1>
    <section>
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using this website, you agree to comply with and be bound by these Terms and Conditions and the Privacy Policy. If you do not agree to these terms, please do not use our website.</p>
    </section>

    <section>
        <h2>2. Use of the Website</h2>
        <p>2.1 You are granted a limited, non-exclusive, non-transferable license to access and use this website for personal or business purposes.</p>
        <p>2.2 You agree not to engage in any unlawful activities, including but not limited to hacking, unauthorized access, or any actions that could harm the website's integrity or disrupt its operation.</p>
    </section>

    <!-- Include more sections and clauses specific to your business -->

    <section>
        <h2>3. Contact Information</h2>
        <p><div class="text-lg text-teal-500 hover:text-violet-700 space-y-2"><a href="{% url 'shoppers:contact' %}">Contact us</a></div></p>
        <p><div class="text-lg text-teal-500 hover:text-violet-700 space-y-2"><a href="{% url 'shoppers:follow_us' %}">Follow us</a></div></p>
    </section>

    <footer>
        <p>These Terms and Conditions were last updated on 15th October 2023.</p>
    </footer>
{% endblock %}